use TestDB 
select COLUMN_NAME, TABLE_CATALOG, TABLE_SCHEMA,TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS 
where TABLE_CATALOG = 'TestDB'
and TABLE_SCHEMA = 'dbo'
and TABLE_NAME = 'Books_venkat'

select *
FROM INFORMATION_SCHEMA.TABLES 